<?php
   $block = $this->getLayout()
    ->createBlock('Duud\Blog\Block\Comment\Load');
?>
<form method="POST" name="comment_form" id="comment_form">
    <span>Nick Name:<input name="author" id="author" title="author" class="author" type="text"></span>
    <span>Text Comment:<input name="content" id="content" title="content" class="content" type="text"><br></span>
    <span>Email:<input name="email" id="email" title="email" class="email" type="text"></span>
    <input type="hidden" name="post_id" value="<?= $block->getPostID() ?>"/>
    <br><button id="submit_demo_data">Submit Comment</button>
</form>

<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ],function($) {
        $(document).ready(function() {
            $('#comment_form').mage(
                'validation',
                {
                    submitHandler: function(form) {
                        var customurl = "<?= $this->getUrl().'blog/comment/save'?>";
                        $.ajax({
                            url: customurl,
                            data: $('#comment_form').serialize(),
                            type: 'POST',
                            dataType: 'json',
                            showLoader: true,
                            cache: false,
                            success: function(data, status, xhr) {
                                $('#comment-list').append("<div><h4> Author:" + data.author + " </h4><p> Email: " + data.email + "</p><p> Comment:" + data.content + "</p></div>");
                                $("#comment_form").trigger('reset');
                            },
                            error: function (xhr, status, errorThrown) {
                                alert(data);
                                console.log('Error happens. Try again.');
                                console.log(errorThrown);
                            }
                        });
                    }
                }
            );
        });
    });
</script>