<?php
    $comments = $this->getComments();
    if(count($comments) > 0)
    {
        echo "<h4>";
        echo __('Lastest Comment For Post ID: ') . $block->getPostID(); 
        echo "</h4>";
        echo "<h1>Block List Comment</h1>";
        foreach($comments as $item )
        {
            echo "<p>".$item->getContent()."</p>";
        }
    }
    else
        echo "<h3>no comments</h3>";
?>