<h3 class="title">Comments:</h3>
<div class="comment-list" id="comment-list">
    <?php $comments = $this->getComments(); ?>
    <?php foreach($comments as $comment) { ?>
        <h4 class="author">Author: <?= $comment->getAuthor() ?></h4>
        <p class="author-email">Email: <?= $comment->getEmail() ?></p>
        <p class="comment-content">Comment:<?= $comment->getContent() ?></p>
    <?php } ?>
</div>
