<?php

/** @var Duud\BlogSimple\Block\Posts $block */ ?>
    <h1>Duud Posts</h1>
    <?php foreach($block->getPosts() as $post): ?>
        <?php /** @var Duud\BlogSimple\Model\Post */ ?>
            <h2>
                <a href="<?php echo $block->getPostUrl($post);?>"><?php echo $post->getTitle(); ?></a>
            </h2>
                <p><?php echo $post->getContent(); ?></p>
<?php endforeach; ?>